
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Actividad
{

    public int RowID { get; set; }

    public Nullable<int> TipoID { get; set; }

    public string Tema { get; set; }

    public Nullable<int> PrioridadID { get; set; }

    public Nullable<int> EstadoID { get; set; }

    public string Descripcion { get; set; }

    public System.DateTime FechaInicial { get; set; }

    public System.DateTime FechaFinal { get; set; }

    public Nullable<int> TerceroERPID { get; set; }

    public Nullable<int> ContactoID { get; set; }

    public Nullable<int> TipoRelacionID { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    public virtual Tercero Tercero { get; set; }

    public virtual Opcion Opcion2 { get; set; }

    public virtual Contacto Contacto { get; set; }

    public virtual Opcion Opcion3 { get; set; }

}

}
