
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Booking()
    {

        this.EncabezadoMatrizBL = new HashSet<EncabezadoMatrizBL>();

    }


    public int RowID { get; set; }

    public Nullable<int> ProformaID { get; set; }

    public Nullable<int> TipoLlenadoID { get; set; }

    public string Nota { get; set; }

    public string Asunto { get; set; }

    public string CorreoEnvio { get; set; }



    public virtual Proforma Proforma { get; set; }

    public virtual Opcion Opcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EncabezadoMatrizBL> EncabezadoMatrizBL { get; set; }

}

}
