//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalculadoraItems
    {
        public int RowID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<double> CantidadTonelada { get; set; }
        public Nullable<int> NumeroEnvio { get; set; }
        public Nullable<decimal> ToneladaContenedor { get; set; }
        public Nullable<decimal> NumeroContenedor { get; set; }
        public Nullable<double> TRM { get; set; }
        public Nullable<double> TRMCompra { get; set; }
        public Nullable<double> TRMVenta { get; set; }
        public Nullable<int> EmbalajeID { get; set; }
        public Nullable<decimal> PVEBRentabilidadporcentaje { get; set; }
        public Nullable<decimal> PVEBRentabilidad { get; set; }
        public Nullable<decimal> PVEporcentaje { get; set; }
        public Nullable<decimal> PVE { get; set; }
        public Nullable<decimal> MPPCCOPValor { get; set; }
        public Nullable<decimal> MPPCUSDCalculado { get; set; }
        public Nullable<decimal> MPPCUSDValor { get; set; }
        public Nullable<decimal> MPPCCOPCalculado { get; set; }
        public Nullable<decimal> CBrokerUSDCON { get; set; }
        public Nullable<decimal> CBrokerUSDTON { get; set; }
        public Nullable<decimal> CBrokerUSD { get; set; }
        public Nullable<decimal> CBrokerPARTE { get; set; }
        public Nullable<decimal> SGSUSDCON { get; set; }
        public Nullable<decimal> SGSUSDTON { get; set; }
        public Nullable<decimal> SGSUSD { get; set; }
        public Nullable<decimal> SGSPARTE { get; set; }
        public Nullable<decimal> CertificadoCalidadUSDCON { get; set; }
        public Nullable<decimal> CertificadoCalidadUSDTON { get; set; }
        public Nullable<decimal> CertificadoCalidadUSD { get; set; }
        public Nullable<decimal> CertificadoCalidadPARTE { get; set; }
        public Nullable<decimal> TrasiegoUSDCON { get; set; }
        public Nullable<decimal> TrasiegoUSDTON { get; set; }
        public Nullable<decimal> TrasiegoUSD { get; set; }
        public Nullable<decimal> TrasiegoPARTE { get; set; }
        public Nullable<decimal> FlexiTanqueUSDCON { get; set; }
        public Nullable<decimal> FlexiTanqueUSDTON { get; set; }
        public Nullable<decimal> FlexiTanqueUSD { get; set; }
        public Nullable<decimal> FlexiTanquePARTE { get; set; }
        public Nullable<decimal> GPortuarioUSDCON { get; set; }
        public Nullable<decimal> GPortuarioUSDTON { get; set; }
        public Nullable<decimal> GPortuarioUSD { get; set; }
        public Nullable<decimal> GPortuarioPARTE { get; set; }
        public Nullable<decimal> GPMPUSDCON { get; set; }
        public Nullable<decimal> GPMPUSDTON { get; set; }
        public Nullable<decimal> GPMPUSD { get; set; }
        public Nullable<decimal> GPMPPARTE { get; set; }
        public Nullable<decimal> GPLLFlexiUSDCON { get; set; }
        public Nullable<decimal> GPLLFlexiUSDTON { get; set; }
        public Nullable<decimal> GPLLFlexiUSD { get; set; }
        public Nullable<decimal> GPLLFlexiPARTE { get; set; }
        public Nullable<decimal> GPUCLLUSDCON { get; set; }
        public Nullable<decimal> GPUCLLUSDTON { get; set; }
        public Nullable<decimal> GPUCLLUSD { get; set; }
        public Nullable<decimal> GPUCLLPARTE { get; set; }
        public Nullable<decimal> GPUICUSDCON { get; set; }
        public Nullable<decimal> GPUICUSDTON { get; set; }
        public Nullable<decimal> GPUICUSD { get; set; }
        public Nullable<decimal> GPUICPARTE { get; set; }
        public Nullable<decimal> SerpentinUSDCON { get; set; }
        public Nullable<decimal> SerpentinUSDTON { get; set; }
        public Nullable<decimal> SerpentinUSD { get; set; }
        public Nullable<decimal> SerpentinPARTE { get; set; }
        public Nullable<decimal> ComisionACargaUSDCON { get; set; }
        public Nullable<decimal> ComisionACargaUSDTON { get; set; }
        public Nullable<decimal> ComisionACargaUSD { get; set; }
        public Nullable<decimal> ComisionACargaPARTE { get; set; }
        public Nullable<decimal> CACHFUSDCON { get; set; }
        public Nullable<decimal> CACHFUSDTON { get; set; }
        public Nullable<decimal> CACHFUSD { get; set; }
        public Nullable<decimal> CACHFPARTE { get; set; }
        public Nullable<decimal> CACDFUSDCON { get; set; }
        public Nullable<decimal> CACDFUSDTON { get; set; }
        public Nullable<decimal> CACDFUSD { get; set; }
        public Nullable<decimal> CACDFPARTE { get; set; }
        public Nullable<decimal> CACBFUSDCON { get; set; }
        public Nullable<decimal> CACBFUSDTON { get; set; }
        public Nullable<decimal> CACBFUSD { get; set; }
        public Nullable<decimal> CACBFPARTE { get; set; }
        public Nullable<decimal> CACothUSDCON { get; set; }
        public Nullable<decimal> CACothUSDTON { get; set; }
        public Nullable<decimal> CACothUSD { get; set; }
        public Nullable<decimal> CACothPARTE { get; set; }
        public Nullable<decimal> CAChlfUSDCON { get; set; }
        public Nullable<decimal> CAChlfUSDTON { get; set; }
        public Nullable<decimal> CAChlfUSD { get; set; }
        public Nullable<decimal> CAChlfPARTE { get; set; }
        public Nullable<decimal> DiasAlmacenUSDCON { get; set; }
        public Nullable<decimal> DiasAlmacenUSDTON { get; set; }
        public Nullable<decimal> DiasAlmacenUSD { get; set; }
        public Nullable<decimal> DiasAlmacenPARTE { get; set; }
        public Nullable<decimal> DGOaUSDCON { get; set; }
        public Nullable<decimal> DGOaUSDTON { get; set; }
        public Nullable<decimal> DGOaUSD { get; set; }
        public Nullable<decimal> DGOaPARTE { get; set; }
        public Nullable<decimal> FleteTerrUSDCON { get; set; }
        public Nullable<decimal> FleteTerrUSDTON { get; set; }
        public Nullable<decimal> FleteTerrUSD { get; set; }
        public Nullable<decimal> FleteTerrPARTE { get; set; }
        public Nullable<decimal> EDocumentoUSDCON { get; set; }
        public Nullable<decimal> EDocumentoUSDTON { get; set; }
        public Nullable<decimal> EDocumentoUSD { get; set; }
        public Nullable<decimal> EDocumentoPARTE { get; set; }
        public Nullable<decimal> FleteMaritimoUSDCON { get; set; }
        public Nullable<decimal> FleteMaritimoUSDTON { get; set; }
        public Nullable<decimal> FleteMaritimoUSD { get; set; }
        public Nullable<decimal> FleteMaritimoPARTE { get; set; }
        public Nullable<decimal> CLTotalcostoUSDCON { get; set; }
        public Nullable<decimal> CLTotalcostoUSDTON { get; set; }
        public Nullable<decimal> CLTotalcostoUSD { get; set; }
        public Nullable<decimal> CLTotalcostoPARTE { get; set; }
        public Nullable<decimal> CMateriaPUSDCON { get; set; }
        public Nullable<decimal> CMateriaPUSDTON { get; set; }
        public Nullable<decimal> CMateriaPUSD { get; set; }
        public Nullable<decimal> CMateriaPPARTE { get; set; }
        public Nullable<decimal> CTotalUSDCON_usd { get; set; }
        public Nullable<decimal> CTotalUSDTON_usd { get; set; }
        public Nullable<decimal> CTotalPUSD_usd { get; set; }
        public Nullable<decimal> CTotalUSDCON_cop { get; set; }
        public Nullable<decimal> CTotalUSDTON_cop { get; set; }
        public Nullable<decimal> CTotalPUSD_cop { get; set; }
        public Nullable<decimal> DatosVentaUSDPContenedor { get; set; }
        public Nullable<decimal> DatosVentaUSDPorton { get; set; }
        public Nullable<decimal> DatosVentaUSDTotal { get; set; }
        public Nullable<decimal> DatosVentaCOPPContenedor { get; set; }
        public Nullable<decimal> DatosVentaCOPPorton { get; set; }
        public Nullable<decimal> DatosVentaCOPTotal { get; set; }
        public Nullable<decimal> DVAgendamientoPContenedor { get; set; }
        public Nullable<decimal> DVAgendamientoPorton { get; set; }
        public Nullable<decimal> DVAgendamientoTotal { get; set; }
        public Nullable<decimal> DVSeguroPContenedor { get; set; }
        public Nullable<decimal> DVSeguroPorton { get; set; }
        public Nullable<decimal> DVSeguroTotal { get; set; }
        public Nullable<decimal> DVCostoManipulacionPContenedor { get; set; }
        public Nullable<decimal> DVCostoManipulacionPorton { get; set; }
        public Nullable<decimal> DVCostoManipulacionTotal { get; set; }
        public Nullable<decimal> DVTAduanerosPContenedor { get; set; }
        public Nullable<decimal> DVTAduanerosPorton { get; set; }
        public Nullable<decimal> DVTAduanerosTotal { get; set; }
        public Nullable<decimal> DVTDestinoPContenedor { get; set; }
        public Nullable<decimal> DVTDestinoPorton { get; set; }
        public Nullable<decimal> DVTDestinoTotal { get; set; }
        public Nullable<decimal> DVMargenPContenedor { get; set; }
        public Nullable<decimal> DVMargenPorton { get; set; }
        public Nullable<decimal> DVMargenTotal { get; set; }
        public Nullable<decimal> DVUtilidadPContenedor { get; set; }
        public Nullable<decimal> DVUtilidadPorton { get; set; }
        public Nullable<decimal> DVUtilidadTotal { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> CalculadoraID { get; set; }
    
        public virtual Calculadora Calculadora { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Item Item { get; set; }
    }
}
