//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoMadera
    {
        public int RowID { get; set; }
        public string Para { get; set; }
        public int MotonaveID { get; set; }
        public string DescripcionBienes { get; set; }
        public int MatrizBLID { get; set; }
        public int CiudadID { get; set; }
        public Nullable<System.DateTime> DiaInspeccion { get; set; }
        public string Inspector { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual MotoNave MotoNave { get; set; }
        public virtual MatrizBL MatrizBL { get; set; }
    }
}
