
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CertificadoMadera
{

    public int RowID { get; set; }

    public string Para { get; set; }

    public int MotonaveID { get; set; }

    public string DescripcionBienes { get; set; }

    public int MatrizBLID { get; set; }

    public int CiudadID { get; set; }

    public Nullable<System.DateTime> DiaInspeccion { get; set; }

    public string Inspector { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Ciudad Ciudad { get; set; }

    public virtual MotoNave MotoNave { get; set; }

    public virtual MatrizBL MatrizBL { get; set; }

}

}
