//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.Proforma = new HashSet<Proforma>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> IntermediarioID { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public Nullable<int> VendedorID { get; set; }
        public Nullable<int> InspectorID { get; set; }
        public Nullable<int> CalculadoraID { get; set; }
        public Nullable<int> TipoContratoID { get; set; }
        public string Calidad1 { get; set; }
        public string Calidad2 { get; set; }
        public string TerminosCondiciones { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Seguro { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<bool> EmbarqueParcial { get; set; }
        public Nullable<int> UsuarioCreacionID { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioActualizaID { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string Transporte { get; set; }
        public Nullable<int> FormaPagoID { get; set; }
    
        public virtual Tercero Tercero { get; set; }
        public virtual Tercero Tercero1 { get; set; }
        public virtual Tercero Tercero2 { get; set; }
        public virtual Tercero Tercero3 { get; set; }
        public virtual Calculadora Calculadora { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proforma> Proforma { get; set; }
        public virtual Opcion Opcion1 { get; set; }
    }
}
