
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ContactoERP
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContactoERP()
    {

        this.Sucursal = new HashSet<Sucursal>();

        this.Sucursal1 = new HashSet<Sucursal>();

        this.Sucursal2 = new HashSet<Sucursal>();

        this.Sucursal3 = new HashSet<Sucursal>();

        this.Tercero = new HashSet<Tercero>();

    }


    public int RowID { get; set; }

    public Nullable<int> RowIDERP { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Direccion3 { get; set; }

    public string Telefono1 { get; set; }

    public string Telefono2 { get; set; }

    public string Fax { get; set; }

    public string CodigoPostal { get; set; }

    public Nullable<int> CiudadID { get; set; }

    public string Email { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public string Identificacion { get; set; }



    public virtual Ciudad Ciudad { get; set; }

    public virtual Ciudad Ciudad1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sucursal> Sucursal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sucursal> Sucursal1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sucursal> Sucursal2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sucursal> Sucursal3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tercero> Tercero { get; set; }

}

}
