
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contrato
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contrato()
    {

        this.DCD = new HashSet<DCD>();

        this.SolicitudLlenado = new HashSet<SolicitudLlenado>();

        this.SolicitudTransporte = new HashSet<SolicitudTransporte>();

        this.OrdenCompra = new HashSet<OrdenCompra>();

        this.MatrizBL = new HashSet<MatrizBL>();

    }


    public int RowID { get; set; }

    public string Intermediario { get; set; }

    public int ProformaID { get; set; }

    public string Calidad { get; set; }

    public int EmbarqueID { get; set; }

    public string Seguro { get; set; }

    public string Inspector { get; set; }

    public string EmbarqueParcial { get; set; }

    public string Titulo { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioActualizacion { get; set; }

    public Nullable<System.DateTime> FechaActualizacion { get; set; }

    public Nullable<int> TipoContratoID { get; set; }

    public string Transporte { get; set; }

    public string Calidad2 { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DCD> DCD { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SolicitudLlenado> SolicitudLlenado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SolicitudTransporte> SolicitudTransporte { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }

    public virtual Proforma Proforma { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MatrizBL> MatrizBL { get; set; }

}

}
