//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contrato()
        {
            this.DCD = new HashSet<DCD>();
            this.SolicitudLlenado = new HashSet<SolicitudLlenado>();
            this.SolicitudTransporte = new HashSet<SolicitudTransporte>();
            this.OrdenCompra = new HashSet<OrdenCompra>();
            this.MatrizBL = new HashSet<MatrizBL>();
        }
    
        public int RowID { get; set; }
        public string Intermediario { get; set; }
        public int ProformaID { get; set; }
        public string Calidad { get; set; }
        public int EmbarqueID { get; set; }
        public string Seguro { get; set; }
        public int TransporteID { get; set; }
        public string Inspector { get; set; }
        public string EmbarqueParcial { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> TipoContratoID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DCD> DCD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudLlenado> SolicitudLlenado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudTransporte> SolicitudTransporte { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }
        public virtual Proforma Proforma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrizBL> MatrizBL { get; set; }
        public virtual Opcion Opcion2 { get; set; }
    }
}
