
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Contacto
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Contacto()
    {

        this.Actividad = new HashSet<Actividad>();

        this.TerceroPotencial = new HashSet<TerceroPotencial>();

    }


    public int RowID { get; set; }

    public string Nombre { get; set; }

    public string Identificacion { get; set; }

    public string Apellido { get; set; }

    public string Direccion1 { get; set; }

    public string Direccion2 { get; set; }

    public string Direccion3 { get; set; }

    public string Telefono1 { get; set; }

    public string Telefono2 { get; set; }

    public string Fax { get; set; }

    public string CodigoPostal { get; set; }

    public Nullable<int> CiudadID { get; set; }

    public string Email { get; set; }

    public string Skype { get; set; }

    public string Descripcion { get; set; }

    public string ruta_imagen { get; set; }

    public string Celular { get; set; }

    public string Cargo { get; set; }

    public string Area { get; set; }

    public Nullable<int> SucursalID { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Actividad> Actividad { get; set; }

    public virtual Ciudad Ciudad { get; set; }

    public virtual Sucursal Sucursal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TerceroPotencial> TerceroPotencial { get; set; }

}

}
