
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Costo
{

    public int RowID { get; set; }

    public string Nombre { get; set; }

    public Nullable<int> MonedaID { get; set; }

    public Nullable<int> TipoID { get; set; }

    public Nullable<double> CostoContenedor { get; set; }

    public Nullable<double> CostoTonelada { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

}

}
