
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empaque
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empaque()
    {

        this.DetalleEmpaque = new HashSet<DetalleEmpaque>();

    }


    public int rowid { get; set; }

    public Nullable<int> puertoCarga { get; set; }

    public Nullable<int> puertoDescarga { get; set; }

    public string shipper { get; set; }

    public string notify { get; set; }

    public Nullable<System.DateTime> exportDate { get; set; }

    public Nullable<double> gross { get; set; }

    public Nullable<double> net { get; set; }

    public Nullable<int> producto { get; set; }

    public Nullable<int> packing { get; set; }

    public string vessel { get; set; }

    public Nullable<int> BlNumber { get; set; }

    public string titulo { get; set; }

    public Nullable<int> subtitulo { get; set; }

    public string para { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleEmpaque> DetalleEmpaque { get; set; }

    public virtual MatrizBL MatrizBL { get; set; }

    public virtual Puerto Puerto { get; set; }

    public virtual Puerto Puerto1 { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Item Item { get; set; }

}

}
