
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Empresa
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Empresa()
    {

        this.Compañia = new HashSet<Compañia>();

    }


    public int RowID { get; set; }

    public Nullable<int> RowIDERP { get; set; }

    public string Nit { get; set; }

    public string RazonSocial { get; set; }

    public Nullable<bool> Activo { get; set; }

    public Nullable<int> ErpID { get; set; }

    public Nullable<int> IdiomaID { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Compañia> Compañia { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

}

}
