
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EncabezadoMatrizBL
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EncabezadoMatrizBL()
    {

        this.DetalleMatrizBL = new HashSet<DetalleMatrizBL>();

        this.ListaEmpaque = new HashSet<ListaEmpaque>();

    }


    public int RowID { get; set; }

    public Nullable<int> BookingID { get; set; }

    public string Descripcion { get; set; }

    public string UnidadMedida { get; set; }

    public Nullable<bool> PrintLading { get; set; }

    public string Consignatario { get; set; }

    public string Notificacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<int> UsuarioCreacionID { get; set; }

    public Nullable<int> TipoEmpaqueID { get; set; }



    public virtual Booking Booking { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetalleMatrizBL> DetalleMatrizBL { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Usuario Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ListaEmpaque> ListaEmpaque { get; set; }

}

}
