
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EnvioMail
{

    public int rowid { get; set; }

    public string MTo { get; set; }

    public string MFrom { get; set; }

    public string Asunto { get; set; }

    public string Mensaje { get; set; }

    public string CreadoPor { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public System.DateTime FechaEnviado { get; set; }

    public Nullable<int> sent { get; set; }

    public string Adjunto { get; set; }

}

}
