
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Estado
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Estado()
    {

        this.AutorizacionCargue = new HashSet<AutorizacionCargue>();

        this.OrdenCompra = new HashSet<OrdenCompra>();

    }


    public int RowID { get; set; }

    public Nullable<int> AgrupacionID { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public Nullable<bool> Activo { get; set; }

    public string UsuarioCreacion { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AutorizacionCargue> AutorizacionCargue { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }

    public virtual Agrupacion Agrupacion { get; set; }

}

}
