
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Factura
{

    public int RowID { get; set; }

    public Nullable<int> ProformaID { get; set; }

    public string Nota { get; set; }

    public Nullable<double> FOB { get; set; }

    public Nullable<double> Flete { get; set; }

    public Nullable<double> Seguro { get; set; }

    public Nullable<double> Cantidad { get; set; }

    public Nullable<double> ValorUnitario { get; set; }

    public Nullable<double> Total { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }



    public virtual Proforma Proforma { get; set; }

}

}
