
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FEP
{

    public int RowID { get; set; }

    public Nullable<int> DCDID { get; set; }

    public string Dex { get; set; }

    public string NCertificadoCP { get; set; }



    public virtual DCD DCD { get; set; }

}

}
