
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Firma
{

    public int RowID { get; set; }

    public string Descripcion { get; set; }

    public string Imagen { get; set; }

    public Nullable<int> TipoFirmaID { get; set; }

    public Nullable<int> UsuarioID { get; set; }



    public virtual Opcion Opcion { get; set; }

    public virtual Usuario Usuario { get; set; }

}

}
