
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {

        this.CalculadoraItems = new HashSet<CalculadoraItems>();

        this.Empaque = new HashSet<Empaque>();

        this.CertificadoCalidad = new HashSet<CertificadoCalidad>();

        this.OrdenCompraItem = new HashSet<OrdenCompraItem>();

        this.Precio = new HashSet<Precio>();

    }


    public int RowID { get; set; }

    public string RowIDERP { get; set; }

    public Nullable<int> CompañiaID { get; set; }

    public string Referencia { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionExtensa { get; set; }

    public string Unidad { get; set; }

    public string UnidadVenta { get; set; }

    public Nullable<bool> Venta { get; set; }

    public Nullable<bool> Compra { get; set; }

    public string Embalaje { get; set; }

    public string CodigoBarras { get; set; }

    public Nullable<double> Impuesto { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalculadoraItems> CalculadoraItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empaque> Empaque { get; set; }

    public virtual Compañia Compañia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CertificadoCalidad> CertificadoCalidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompraItem> OrdenCompraItem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Precio> Precio { get; set; }

}

}
