
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Item
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Item()
    {

        this.CalculadoraItems = new HashSet<CalculadoraItems>();

        this.OrdenCompraItem = new HashSet<OrdenCompraItem>();

        this.OrdenCompraItem1 = new HashSet<OrdenCompraItem>();

        this.Precio = new HashSet<Precio>();

        this.ItemImpuesto = new HashSet<ItemImpuesto>();

    }


    public int RowID { get; set; }

    public string RowIDERP { get; set; }

    public Nullable<int> CompañiaID { get; set; }

    public string Referencia { get; set; }

    public string Codigo { get; set; }

    public string Descripcion { get; set; }

    public string DescripcionExtensa { get; set; }

    public string Unidad { get; set; }

    public string UnidadVenta { get; set; }

    public Nullable<bool> Venta { get; set; }

    public Nullable<bool> Compra { get; set; }

    public string Embalaje { get; set; }

    public string CodigoBarras { get; set; }

    public Nullable<double> Impuesto { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    public virtual Compañia Compañia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalculadoraItems> CalculadoraItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompraItem> OrdenCompraItem { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompraItem> OrdenCompraItem1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Precio> Precio { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ItemImpuesto> ItemImpuesto { get; set; }

}

}
