
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class m_plantillas
{

    public int RowID { get; set; }

    public Nullable<int> RowID_Empresa { get; set; }

    public string Tipo_Plantilla { get; set; }

    public string Nombre { get; set; }

    public string Header { get; set; }

    public string Body { get; set; }

    public string Query { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string Tags { get; set; }

    public Nullable<int> Secuencia { get; set; }

    public string Detail { get; set; }

}

}
