
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MatrizBL
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MatrizBL()
    {

        this.Empaque = new HashSet<Empaque>();

        this.CertificadoCalidad = new HashSet<CertificadoCalidad>();

        this.CertificadoMadera = new HashSet<CertificadoMadera>();

    }


    public int RowID { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public string NumeroReserva { get; set; }

    public string Expedidor { get; set; }

    public int EmpresaID { get; set; }

    public string Consignee { get; set; }

    public string Notificacion { get; set; }

    public int ContratoID { get; set; }

    public Nullable<int> NCM { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Empaque> Empaque { get; set; }

    public virtual Tercero Tercero { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CertificadoCalidad> CertificadoCalidad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CertificadoMadera> CertificadoMadera { get; set; }

    public virtual Contrato Contrato { get; set; }

}

}
