
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrdenCompraContrato
{

    public int RowID { get; set; }

    public Nullable<int> OrdenCompraID { get; set; }

    public Nullable<int> ContratoID { get; set; }

    public Nullable<bool> AgregarItems { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Contrato Contrato { get; set; }

    public virtual Contrato Contrato1 { get; set; }

    public virtual OrdenCompra OrdenCompra { get; set; }

    public virtual OrdenCompra OrdenCompra1 { get; set; }

}

}
