
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrdenCompraContrato
{

    public int RowID { get; set; }

    public Nullable<int> OrdenCompraID { get; set; }

    public Nullable<int> ContratoID { get; set; }

    public Nullable<bool> AgregarItems { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }



    public virtual Contrato Contrato { get; set; }

    public virtual Contrato Contrato1 { get; set; }

    public virtual OrdenCompra OrdenCompra { get; set; }

    public virtual OrdenCompra OrdenCompra1 { get; set; }

}

}
