//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Precio
    {
        public int RowID { get; set; }
        public Nullable<int> RowIDERP { get; set; }
        public Nullable<int> ListaPrecioID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> ItemExtensionID { get; set; }
        public string Unidad { get; set; }
        public double Precio1 { get; set; }
        public Nullable<System.DateTime> FechaActivacion { get; set; }
        public Nullable<System.DateTime> FechaInactivacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ListaPrecio ListaPrecio { get; set; }
    }
}
