//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProformaItemCalculadora
    {
        public int RowID { get; set; }
        public Nullable<int> ProformaID { get; set; }
        public Nullable<int> ItemCalculadoraID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> PrecioCombrar { get; set; }
        public Nullable<int> UsuarioCreacionID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioActualizaID { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual CalculadoraItems CalculadoraItems { get; set; }
        public virtual Proforma Proforma { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
