
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProformaItemCalculadora
{

    public int RowID { get; set; }

    public Nullable<int> ProformaID { get; set; }

    public Nullable<int> ItemCalculadoraID { get; set; }

    public Nullable<int> Cantidad { get; set; }

    public Nullable<double> PrecioCombrar { get; set; }

    public Nullable<int> UsuarioCreacionID { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<int> UsuarioActualizaID { get; set; }

    public Nullable<System.DateTime> FechaActualizacion { get; set; }

    public Nullable<double> FobTonelada { get; set; }

    public Nullable<double> FleteTonelada { get; set; }

    public Nullable<double> SeguroTonelada { get; set; }

    public Nullable<double> CifTonelada { get; set; }

    public Nullable<double> FobValor { get; set; }

    public Nullable<double> FleteValor { get; set; }

    public Nullable<double> SeguroValor { get; set; }

    public Nullable<double> CifValor { get; set; }



    public virtual CalculadoraItems CalculadoraItems { get; set; }

    public virtual Proforma Proforma { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual Usuario Usuario1 { get; set; }

}

}
