//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proforma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proforma()
        {
            this.ProformaItemCalculadora = new HashSet<ProformaItemCalculadora>();
        }
    
        public int RowID { get; set; }
        public string Titulo { get; set; }
        public Nullable<int> FormaPagoID { get; set; }
        public Nullable<int> ContratoID { get; set; }
        public Nullable<int> PuertoCargueID { get; set; }
        public Nullable<int> PuertoDescargueID { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public Nullable<int> UsuarioCreacionID { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> UsuarioActualizaID { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> TipoProformaID { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual Opcion Opcion { get; set; }
        public virtual Puerto Puerto { get; set; }
        public virtual Puerto Puerto1 { get; set; }
        public virtual Opcion Opcion1 { get; set; }
        public virtual Opcion Opcion2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProformaItemCalculadora> ProformaItemCalculadora { get; set; }
    }
}
