
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Proforma
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Proforma()
    {

        this.Contrato = new HashSet<Contrato>();

        this.RecursosProforma = new HashSet<RecursosProforma>();

    }


    public int RowID { get; set; }

    public Nullable<int> CalculadoraID { get; set; }

    public string Titulo { get; set; }

    public string Nit { get; set; }

    public Nullable<System.DateTime> Fecha { get; set; }

    public Nullable<int> VendedorID { get; set; }

    public Nullable<int> CompradorID { get; set; }

    public Nullable<int> TipoPagoID { get; set; }

    public Nullable<int> PuertoCargueID { get; set; }

    public Nullable<int> PuertoDescargueID { get; set; }

    public Nullable<System.DateTime> FechaEnvio { get; set; }

    public string NumeroContrato { get; set; }

    public string Observaciones { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public Nullable<int> TipoProformaID { get; set; }



    public virtual Calculadora Calculadora { get; set; }

    public virtual Tercero Tercero { get; set; }

    public virtual Tercero Tercero1 { get; set; }

    public virtual Opcion Opcion { get; set; }

    public virtual Opcion Opcion1 { get; set; }

    public virtual Puerto Puerto { get; set; }

    public virtual Puerto Puerto1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contrato> Contrato { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RecursosProforma> RecursosProforma { get; set; }

}

}
