
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProformaItemCalculadora
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProformaItemCalculadora()
    {

        this.EncabezadoRegistroLlenado = new HashSet<EncabezadoRegistroLlenado>();

    }


    public int RowID { get; set; }

    public Nullable<int> ProformaID { get; set; }

    public Nullable<int> ItemCalculadoraID { get; set; }

    public Nullable<int> Cantidad { get; set; }

    public Nullable<double> PrecioCombrar { get; set; }

    public Nullable<int> UsuarioCreacionID { get; set; }

    public Nullable<System.DateTime> FechaCreacion { get; set; }

    public Nullable<int> UsuarioActualizaID { get; set; }

    public Nullable<System.DateTime> FechaActualizacion { get; set; }

    public Nullable<double> FobTonelada { get; set; }

    public Nullable<double> FleteTonelada { get; set; }

    public Nullable<double> SeguroTonelada { get; set; }

    public Nullable<double> CifTonelada { get; set; }

    public Nullable<double> FobValor { get; set; }

    public Nullable<double> FleteValor { get; set; }

    public Nullable<double> SeguroValor { get; set; }

    public Nullable<double> CifValor { get; set; }

    public Nullable<int> Porcentaje { get; set; }



    public virtual CalculadoraItems CalculadoraItems { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EncabezadoRegistroLlenado> EncabezadoRegistroLlenado { get; set; }

    public virtual Proforma Proforma { get; set; }

    public virtual Usuario Usuario { get; set; }

    public virtual Usuario Usuario1 { get; set; }

}

}
