
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class PuntoEnvio
{

    public int RowID { get; set; }

    public Nullable<int> RowIDERP { get; set; }

    public Nullable<int> SucursalID { get; set; }

    public Nullable<int> VendedorID { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public Nullable<bool> Activo { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }



    public virtual Sucursal Sucursal { get; set; }

    public virtual Tercero Tercero { get; set; }

}

}
