
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RecursosContrato
{

    public int RowID { get; set; }

    public string Codigo { get; set; }

    public string Archivo { get; set; }

    public int ContratoID { get; set; }



    public virtual RecursosProforma RecursosProforma { get; set; }

}

}
