
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sucursal
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sucursal()
    {

        this.Contacto = new HashSet<Contacto>();

        this.OrdenCompra = new HashSet<OrdenCompra>();

        this.PuntoEnvio = new HashSet<PuntoEnvio>();

    }


    public int RowID { get; set; }

    public string RowIDERP { get; set; }

    public string Nombre { get; set; }

    public Nullable<int> CompañiaID { get; set; }

    public Nullable<int> TerceroID { get; set; }

    public Nullable<int> VendedorID { get; set; }

    public Nullable<int> ContactoERPID { get; set; }

    public Nullable<int> ListaPrecioID { get; set; }

    public string TipoSucursalID { get; set; }

    public Nullable<int> CondicionID { get; set; }

    public string CentroOperacion { get; set; }

    public Nullable<bool> BloqueoCupo { get; set; }

    public Nullable<bool> BloqueoMora { get; set; }

    public Nullable<double> CupoCredito { get; set; }

    public System.DateTime FechaCreacion { get; set; }

    public string UsuarioCreacion { get; set; }

    public Nullable<System.DateTime> FechaModificacion { get; set; }

    public string UsuarioModificacion { get; set; }

    public string Codigo { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Contacto> Contacto { get; set; }

    public virtual Compañia Compañia { get; set; }

    public virtual Compañia Compañia1 { get; set; }

    public virtual Compañia Compañia2 { get; set; }

    public virtual Compañia Compañia3 { get; set; }

    public virtual CondicionPago CondicionPago { get; set; }

    public virtual ContactoERP ContactoERP { get; set; }

    public virtual ContactoERP ContactoERP1 { get; set; }

    public virtual ContactoERP ContactoERP2 { get; set; }

    public virtual ContactoERP ContactoERP3 { get; set; }

    public virtual ListaPrecio ListaPrecio { get; set; }

    public virtual ListaPrecio ListaPrecio1 { get; set; }

    public virtual ListaPrecio ListaPrecio2 { get; set; }

    public virtual ListaPrecio ListaPrecio3 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrdenCompra> OrdenCompra { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PuntoEnvio> PuntoEnvio { get; set; }

    public virtual Tercero Tercero { get; set; }

    public virtual Tercero Tercero1 { get; set; }

    public virtual Tercero Tercero2 { get; set; }

    public virtual Tercero Tercero3 { get; set; }

    public virtual Tercero Tercero4 { get; set; }

    public virtual Tercero Tercero5 { get; set; }

    public virtual Tercero Tercero6 { get; set; }

    public virtual Tercero Tercero7 { get; set; }

}

}
