
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VehiculoSolicitudLlenado
{

    public int RowID { get; set; }

    public Nullable<System.DateTime> FechaCargue { get; set; }

    public int VehiculoID { get; set; }

    public string Remolque { get; set; }

    public int EmpresaTransporteID { get; set; }

    public int TerceroID { get; set; }

    public int SolicitudLlenadoID { get; set; }



    public virtual SolicitudLlenado SolicitudLlenado { get; set; }

    public virtual Vehiculo Vehiculo { get; set; }

    public virtual Compañia Compañia { get; set; }

    public virtual Tercero Tercero { get; set; }

}

}
