
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PedidosOnline.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VehiculoSolicitudLlenado
{

    public int RowID { get; set; }

    public Nullable<System.DateTime> FechaCargue { get; set; }

    public int VehiculoID { get; set; }

    public string Remolque { get; set; }

    public int EmpresaTransporteID { get; set; }

    public int TerceroID { get; set; }

    public int SolicitudLlenadoID { get; set; }



    public virtual SolicitudLlenado SolicitudLlenado { get; set; }

    public virtual Vehiculo Vehiculo { get; set; }

    public virtual Compañia Compañia { get; set; }

    public virtual Tercero Tercero { get; set; }

}

}
